KEYMAP='us'
LANG='en_US'
TIMEZONE='Europe/Berlin'
FONT=Lat2-Terminus16

BLOCKDEVICEDISK=/dev/sda
BLOCKDEVICEBOOT=/dev/sda1
BLOCKDEVICESWAP=/dev/sda2
BLOCKDEVICEROOT=/dev/sda3

MNT=/mnt

HOSTNAME=archbox
DEFAULTUSER=deccer
